import crypto from 'node:crypto';
import { validateNewCase, nextStage, nextStageDueAt, assertClosureAllowed } from '../accountability.mjs';

export class PostgresStore {
  constructor(pool){ this.pool=pool; }
  static async create(config){ const {Pool}=await import('pg'); const pool=new Pool({connectionString:config.databaseUrl,ssl:config.databaseSsl?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000}); return new PostgresStore(pool); }
  async tx(actor,fn){ const client=await this.pool.connect(); try{ await client.query('BEGIN'); await client.query("SELECT set_config('app.tenant_id',$1,true), set_config('app.user_id',$2,true)",[actor.tenantId,actor.id]); const result=await fn(client); await client.query('COMMIT'); return result; }catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
  async readiness(){ const result=await this.pool.query('SELECT current_database() AS database, now() AS checked_at'); return {adapter:'postgres',persistent:true,appendOnlyEvents:true,database:result.rows[0].database,checkedAt:result.rows[0].checked_at}; }
  async listCases(actor){ return this.tx(actor,async c=>(await c.query('SELECT * FROM accountability_cases WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 250',[actor.tenantId])).rows); }
  async getCase(actor,id){ return this.tx(actor,async c=>(await c.query('SELECT * FROM accountability_cases WHERE id=$1 AND tenant_id=$2',[id,actor.tenantId])).rows[0]||null); }
  async createCase(input){ validateNewCase(input); const actor={tenantId:input.tenantId,id:input.createdBy}; return this.tx(actor,async c=>{ const id=crypto.randomUUID(); const r=await c.query(`INSERT INTO accountability_cases(id,tenant_id,sector_id,title,summary,stage,status,primary_owner_id,backup_owner_id,due_at,stage_due_at,created_by) VALUES($1,$2,$3,$4,$5,'GREEN','ASSIGNED',$6,$7,$8,$8,$9) RETURNING *`,[id,input.tenantId,input.sectorId,input.title,input.summary,input.primaryOwnerId,input.backupOwnerId,input.dueAt,input.createdBy]); await event(c,r.rows[0],input.createdBy,'CASE_CREATED',{primaryOwnerId:input.primaryOwnerId,backupOwnerId:input.backupOwnerId,dueAt:input.dueAt}); return r.rows[0]; }); }
  async accept(actor,id){ return this.tx(actor,async c=>{ const found=(await c.query('SELECT * FROM accountability_cases WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!found)return null; const now=new Date().toISOString(); const r=await c.query("UPDATE accountability_cases SET accepted_at=$1,accepted_by=$2,status='ACCEPTED',updated_at=$1 WHERE id=$3 RETURNING *",[now,actor.id,id]); await event(c,r.rows[0],actor.id,'ASSIGNMENT_ACCEPTED',{}); return r.rows[0]; }); }
  async recordAction(actor,id,input){ return this.tx(actor,async c=>{ const action=String(input.actionSummary||'').trim(); if(!action){const e=new Error('actionSummary is required.');e.status=400;throw e} const r=await c.query("UPDATE accountability_cases SET action_summary=$1,outcome_summary=NULLIF($2,''),residual_risk=NULLIF($3,''),status='ACTIONED',updated_at=now() WHERE id=$4 RETURNING *",[action,String(input.outcomeSummary||''),String(input.residualRisk||''),id]); if(!r.rows[0])return null; await event(c,r.rows[0],actor.id,'ACTION_RECORDED',{actionSummary:action,outcomeSummary:input.outcomeSummary,residualRisk:input.residualRisk}); return r.rows[0]; }); }
  async escalate(actor,id,input={}){ return this.tx(actor,async c=>{ const found=(await c.query('SELECT * FROM accountability_cases WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!found)return null; const to=nextStage(found.stage); const nextDue=nextStageDueAt(to); const r=await c.query("UPDATE accountability_cases SET stage=$1,stage_due_at=$2,escalation_count=escalation_count+1,status=CASE WHEN $1='GOVERNANCE' THEN 'UNDER_REVIEW' ELSE status END,updated_at=now() WHERE id=$3 RETURNING *",[to,nextDue,id]); await event(c,r.rows[0],actor.id,'CASE_ESCALATED',{from:found.stage,to,reason:String(input.reason||'Timed or manual escalation')}); return r.rows[0]; }); }
  async close(actor,id,input){ return this.tx(actor,async c=>{ const found=(await c.query('SELECT * FROM accountability_cases WHERE id=$1 FOR UPDATE',[id])).rows[0]; if(!found)return null; assertClosureAllowed(found,input,actor); const r=await c.query("UPDATE accountability_cases SET action_summary=$1,outcome_summary=$2,residual_risk=$3,governance_signoff_by=$4,governance_signoff_at=now(),closed_at=now(),status='CLOSED',updated_at=now() WHERE id=$5 RETURNING *",[input.actionSummary||found.action_summary,input.outcomeSummary||found.outcome_summary,input.residualRisk||found.residual_risk,actor.id,id]); await event(c,r.rows[0],actor.id,'CASE_CLOSED',{outcomeSummary:r.rows[0].outcome_summary,evidenceReference:input.evidenceReference,residualRisk:r.rows[0].residual_risk}); return r.rows[0]; }); }

  async escalateOverdueSystem(now=new Date()){
    const tenants=(await this.pool.query('SELECT id FROM tenants ORDER BY id')).rows.map(r=>r.id); const ids=[];
    for(const tenantId of tenants){
      const actor={tenantId,id:'system-escalation-worker'};
      const changed=await this.tx(actor,async c=>{
        const due=(await c.query("SELECT * FROM accountability_cases WHERE tenant_id=$1 AND status<>'CLOSED' AND stage_due_at IS NOT NULL AND stage_due_at<=$2 ORDER BY stage_due_at FOR UPDATE SKIP LOCKED LIMIT 100",[tenantId,now.toISOString()])).rows; const local=[];
        for(const found of due){ const to=nextStage(found.stage); const nextDue=nextStageDueAt(to,now); const result=await c.query("UPDATE accountability_cases SET stage=$1,stage_due_at=$2,escalation_count=escalation_count+1,status=CASE WHEN $1='GOVERNANCE' THEN 'UNDER_REVIEW' ELSE status END,updated_at=$3 WHERE id=$4 RETURNING *",[to,nextDue,now.toISOString(),found.id]); await event(c,result.rows[0],actor.id,'TIMED_ESCALATION',{from:found.stage,to,overdueAt:found.stage_due_at}); local.push(found.id); }
        return local;
      }); ids.push(...changed);
    }
    return {count:ids.length,caseIds:ids,checkedAt:now.toISOString()};
  }
  async history(actor,id){ return this.tx(actor,async c=>(await c.query('SELECT * FROM case_events WHERE case_id=$1 ORDER BY occurred_at,id',[id])).rows); }
}
async function event(c,item,actorId,type,detail){ await c.query('INSERT INTO case_events(id,tenant_id,case_id,event_type,actor_id,detail) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[crypto.randomUUID(),item.tenant_id,item.id,type,actorId||'system',JSON.stringify(detail||{})]); }
